BUSINESS_SYNONYMS: dict[str, list[str]] = {
    "faturamento": [
        "vendas",
        "venda",
        "receita",
        "faturamento",
        "valor vendido",
        "valor de venda",
        "total vendido",
        "venderam",
        "vendeu",
        "vendido",
    ],
    "cliente": [
        "cliente",
        "clientes",
        "consumidor",
        "consumidores",
        "comprador",
        "compradores",
    ],
    "shopping": [
        "shopping",
        "shoppings",
        "empreendimento",
        "empreendimentos",
        "mall",
        "malls",
    ],
    "loja": [
        "loja",
        "lojas",
        "lojista",
        "lojistas",
        "operação",
        "operações",
        "unidade",
        "unidades",
    ],
    "restaurante": [
        "restaurante",
        "restaurantes",
        "alimentação",
        "food",
        "food court",
        "praça de alimentação",
    ],
    "promocao": [
        "campanha",
        "campanhas",
        "promoção",
        "promocao",
        "promoções",
        "promocoes",
        "ação promocional",
        "acao promocional",
        "ações promocionais",
        "acoes promocionais",
    ],
    "data": [
        "data",
        "período",
        "periodo",
        "mês",
        "mes",
        "ano",
        "dia",
    ],
    "ticket_medio": [
        "ticket médio",
        "ticket medio",
        "tm",
        "valor médio",
        "valor medio",
        "média por compra",
        "media por compra",
    ],
    "crescimento": [
        "crescimento",
        "variação",
        "variacao",
        "evolução",
        "evolucao",
        "aumento",
        "queda",
    ],
    "ranking": [
        "ranking",
        "top",
        "maior",
        "maiores",
        "melhor",
        "melhores",
        "menor",
        "menores",
        "mais",
    ],
}
